// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/buyer.proto

package auth_crud

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BuyerServiceClient is the client API for BuyerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuyerServiceClient interface {
	CreateBuyer(ctx context.Context, in *Buyersmodel, opts ...grpc.CallOption) (*DBresponse, error)
}

type buyerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuyerServiceClient(cc grpc.ClientConnInterface) BuyerServiceClient {
	return &buyerServiceClient{cc}
}

func (c *buyerServiceClient) CreateBuyer(ctx context.Context, in *Buyersmodel, opts ...grpc.CallOption) (*DBresponse, error) {
	out := new(DBresponse)
	err := c.cc.Invoke(ctx, "/proto.BuyerService/CreateBuyer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuyerServiceServer is the server API for BuyerService service.
// All implementations must embed UnimplementedBuyerServiceServer
// for forward compatibility
type BuyerServiceServer interface {
	CreateBuyer(context.Context, *Buyersmodel) (*DBresponse, error)
	mustEmbedUnimplementedBuyerServiceServer()
}

// UnimplementedBuyerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBuyerServiceServer struct {
}

func (UnimplementedBuyerServiceServer) CreateBuyer(context.Context, *Buyersmodel) (*DBresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuyer not implemented")
}
func (UnimplementedBuyerServiceServer) mustEmbedUnimplementedBuyerServiceServer() {}

// UnsafeBuyerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuyerServiceServer will
// result in compilation errors.
type UnsafeBuyerServiceServer interface {
	mustEmbedUnimplementedBuyerServiceServer()
}

func RegisterBuyerServiceServer(s grpc.ServiceRegistrar, srv BuyerServiceServer) {
	s.RegisterService(&BuyerService_ServiceDesc, srv)
}

func _BuyerService_CreateBuyer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Buyersmodel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuyerServiceServer).CreateBuyer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BuyerService/CreateBuyer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuyerServiceServer).CreateBuyer(ctx, req.(*Buyersmodel))
	}
	return interceptor(ctx, in, info, handler)
}

// BuyerService_ServiceDesc is the grpc.ServiceDesc for BuyerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuyerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BuyerService",
	HandlerType: (*BuyerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBuyer",
			Handler:    _BuyerService_CreateBuyer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/buyer.proto",
}
