// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/buyer.proto

package auth_crud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Buyersmodel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mail        string `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	Age         int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Phonenumber int32  `protobuf:"varint,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Buyersmodel) Reset() {
	*x = Buyersmodel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_buyer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Buyersmodel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buyersmodel) ProtoMessage() {}

func (x *Buyersmodel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_buyer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buyersmodel.ProtoReflect.Descriptor instead.
func (*Buyersmodel) Descriptor() ([]byte, []int) {
	return file_proto_buyer_proto_rawDescGZIP(), []int{0}
}

func (x *Buyersmodel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Buyersmodel) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *Buyersmodel) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Buyersmodel) GetPhonenumber() int32 {
	if x != nil {
		return x.Phonenumber
	}
	return 0
}

func (x *Buyersmodel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DBresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DBresponse) Reset() {
	*x = DBresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_buyer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBresponse) ProtoMessage() {}

func (x *DBresponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_buyer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBresponse.ProtoReflect.Descriptor instead.
func (*DBresponse) Descriptor() ([]byte, []int) {
	return file_proto_buyer_proto_rawDescGZIP(), []int{1}
}

func (x *DBresponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_buyer_proto protoreflect.FileDescriptor

var file_proto_buyer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x0b,
	0x42, 0x75, 0x79, 0x65, 0x72, 0x73, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x44, 0x42, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x46, 0x0a, 0x0c, 0x42, 0x75, 0x79, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x79, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x75,
	0x79, 0x65, 0x72, 0x73, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x44, 0x42, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a,
	0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x61, 0x73, 0x65,
	0x6e, 0x74, 0x68, 0x44, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x63, 0x72, 0x75, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_buyer_proto_rawDescOnce sync.Once
	file_proto_buyer_proto_rawDescData = file_proto_buyer_proto_rawDesc
)

func file_proto_buyer_proto_rawDescGZIP() []byte {
	file_proto_buyer_proto_rawDescOnce.Do(func() {
		file_proto_buyer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_buyer_proto_rawDescData)
	})
	return file_proto_buyer_proto_rawDescData
}

var file_proto_buyer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_buyer_proto_goTypes = []interface{}{
	(*Buyersmodel)(nil), // 0: protos.Buyersmodel
	(*DBresponse)(nil),  // 1: protos.DBresponse
}
var file_proto_buyer_proto_depIdxs = []int32{
	0, // 0: protos.BuyerService.CreateBuyer:input_type -> protos.Buyersmodel
	1, // 1: protos.BuyerService.CreateBuyer:output_type -> protos.DBresponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_buyer_proto_init() }
func file_proto_buyer_proto_init() {
	if File_proto_buyer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_buyer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Buyersmodel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_buyer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_buyer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_buyer_proto_goTypes,
		DependencyIndexes: file_proto_buyer_proto_depIdxs,
		MessageInfos:      file_proto_buyer_proto_msgTypes,
	}.Build()
	File_proto_buyer_proto = out.File
	file_proto_buyer_proto_rawDesc = nil
	file_proto_buyer_proto_goTypes = nil
	file_proto_buyer_proto_depIdxs = nil
}
